### ISSUE TITLE
IGoR crashes when reading mouse V CDR3 anchors

### ISSUE THREAD

**Issue by ingewortel** [qmarcou/IGoR#20] opened 2018-07-31 13:13 UTC
Hi @qmarcou!

I am trying to run IGoR with the standard mouse beta chain model but have some problems with the alignment:

`igor -set_wd . -batch foo -read_seqs myseqs.fasta -species mouse -chain beta -align --all`

yields the following output:

`Batch name set to: foo_`
`FASTA extension detected for the input sequence file`
`Species parameter set to: mouse`
`Chain parameter set to: beta`
`Working directory set to: "./"`
`[IGoR] ERROR: Exception caught while reading V CDR3 anchors.`
`[IGoR] ERROR: stoi`
`[IGoR] ERROR: Use "man igor", "igor -help" or visit https://bitbucket.org/qmarcou/igor to see available commands and their effects.`
`[IGoR] ERROR: Please report any bug to: quentin.marcou@lpt.ens.fr`
`[IGoR] ERROR: Terminating IGoR...`

Note that I don't have this problem when I just read the sequences with 
`igor -set_wd . -batch foo -read_seqs myseqs.fasta`
or try the alignment on the human model with
`igor -set_wd . -batch foo -read_seqs myseqs.fasta -species human -chain beta -align --all`
But I do get the same error about V CDR3 anchors even when I try to align only the J genes:
`igor -set_wd . -batch foo -read_seqs myseqs.fasta -species mouse -chain beta -align --J`

So the issue seems to be in the mouse model itself somewhere and probably has something to do with the _V_gene_CDR3_anchors.csv_ file.

I looked into the _V_gene_CDR3_anchors.csv_ file provided, and noticed that some of the TRBV genes that occur in the _genomicVs.fasta_ file and the _model_parms.txt_ file are missing from the anchor file (for example, TRBV11*01). Could this be why IGoR crashes? Or am I doing something wrong?

Thanks!

Inge

**Comment by qmarcou** [comment] 2018-08-01 15:20
Hi @ingewortel ,
Sorry about that this is a silly mistake on my side, the genomic anchors file should be semicolon separated and not coma separated.
You can hardfix this locally by replacing comas by semicolons in the gene anchors file of your interest (either in the directory IGoR models have been installed into, or before installation)
This is something I should have fixed earlier, I will try and release a new version of IGoR containing this fix along other bug fixes in the next few days.
Again my apologies for this silly mistake...

**Comment by ingewortel** [comment] 2018-08-03 09:01
Hi @qmarcou 

Thanks for the quick reply, 
the semicolons indeed fixed the problem!

Best wishes,
Inge

**Comment by qmarcou** [comment] 2018-08-04 19:44
Hi @ingewortel ,
I have uploaded IGoRv1.3.0 release in which your problem has been addressed, along many others and new features were added. Check it out!
I'll thus close this issue since the problem is solved.
Best wished

**Closed by qmarcou** 2018-08-04 19:44 UTC
Labels: bug, fixed on dev branch
