### ISSUE TITLE
Compilation Issue with igor.1 missing

### ISSUE THREAD

**Issue by NickEngland** [qmarcou/IGoR#10] opened 2018-06-11 12:17 UTC
When running make:

make[2]: *** No rule to make target `igor.1', needed by `all-am'. Stop.

When the autogen.sh runs, I get the following:

pandoc -s -f markdown -t man README.md -o igor.1
pandoc: README.md: openFile: does not exist (No such file or directory)

Doing:
asciidoc -b docbook README.adoc
pandoc -f docbook -t markdown_strict README.xml -o README.md
(from https://tinyapps.org/blog/nix/201701240700_convert_asciidoc_to_markdown.html)

Seems to resolve the issue.

Perhaps these steps should be added to the autogen.sh? Or am I missing some dependency?

**Comment by qmarcou** [comment] 2018-06-15 21:08
Hi!
Again thank you for pointing this out, the issue is now fixed on the `dev` branch and will be up in the new version.

**Closed by qmarcou** 2018-06-15 21:08 UTC
Labels: bug
